name: CI/CD with Terraform

on:
  push:
    branches: 
     = master
env:
    AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    TF_STATE_BUCKET_NAME: ${{ secrets.AWS_TF_STATE_BUCKET_NAME }}
    PRIVATE_SSH_KEY: ${{ secrets.AWS_SSH_KEY_PRIVATE }}
    PUBLIC_SSH_KEY: ${{ secrets.AWS_SSH_KEY_PUBLIC }}
    AWS_REGION: ${{ secrets.AWS_REGION }}
jobs:
    initialize-infra:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Setup Terraform
              uses: hashicorp/setup-terraform@v1  
              with:
                terraform_wrapper: false 
            - name: Terraform Init
              id: init
              run: terraform init -backend-config="bucket=${{ env.TF_STATE_BUCKET_NAME }}" -backend-config="region=us-east-1"
              working-directory: ./terraform
    plan-infra:
        runs-on: ubuntu-latest
        steps:
            - name: Terraform plan
              id: plan
              run: |-
                terraform plan \
                -var="region=us-east-1" \
                -var="public_key=$PUBLIC_SSH_KEY" \
                -var="private_key=$PRIVATE_SSH_KEY" \
                -VAR="key_name=deploy-key" \
                -out=PLAN
              working-directory: ./terraform

    apply-infra:
        runs-on: ubuntu-latest
        steps: 
            - name: Terraform apply
              id: apply
              run: terraform apply PLAN
              working-directory: ./terraform
